[project]
name = "css-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "manim>=0.19.2",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "streamlit>=1.53.1",
]
